# Generated by Django 5.1.6 on 2025-05-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_article_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
