# Generated by Django 5.1.6 on 2025-03-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_name_post_title_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Post Categories'},
        ),
    ]
