# Generated by Django 5.1.7 on 2025-03-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='title',
            new_name='name',
        ),
    ]
